apiVersion: v1
kind: ServiceAccount
metadata:
  name: accounts-api
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377181070:role/AccountsAPI-EKS-ServiceAccount-Role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: accounts-api
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: accounts-api
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: accounts-api
subjects:
- kind: ServiceAccount
  name: accounts-api
  namespace: default
